spring.application.name=dslist

spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false

# Rawg API Config
rawg.api.key=${RAWG_API_KEY}
rawg.api.url=https://api.rawg.io/api

# Google OAuth2 Config
spring.security.oauth2.client.registration.google.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

# O cors da porta 4200 (Angular) está configurado na classe SecurityConfig no metodo corsConfigurationSource(), que é uma outra forma de fazer